# Generated by Django 6.0.4 on 2026-05-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testquestion_remove_video_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='lesson_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='main.video', verbose_name='Video dars'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='lesson_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='main.video', verbose_name='Video dars'),
        ),
    ]
