# Generated by Django 6.0.4 on 2026-05-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_book_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
