# Generated by Django 6.0.4 on 2026-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_role_to_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_paid',
            field=models.BooleanField(default=False, help_text="Pullik dars bo'lsa True"),
        ),
    ]
