# Generated by Django 6.0.4 on 2026-05-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_payment_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_url',
            new_name='video_url',
        ),
    ]
