# Generated by Django 6.0.4 on 2026-05-30 11:09

import main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_revert_video_file_to_local_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=main.storage.BunnyStorage, upload_to='videos/'),
        ),
    ]
