# Generated by Django 6.0.4 on 2026-05-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_created_by_to_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Karta egasining ismi', max_length=200)),
                ('card_number', models.CharField(help_text='Karta raqami: 8600 0000 0000 0000', max_length=19)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "To'lov kartasi",
                'verbose_name_plural': "To'lov kartalari",
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, help_text='Masalan: Dushanba–Juma: 09:00–18:00', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=41.2995, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=69.2401, max_digits=9)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
