# Generated by Django 6.0.4 on 2026-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='subscription_days',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
