# Generated by Django 6.0.4 on 2026-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_subscription_remove_expires_payment_remove_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='course_price',
            field=models.PositiveIntegerField(default=0, help_text="Kurs narxi (so'mda)"),
        ),
    ]
