# Generated by Django 6.0.4 on 2026-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='receipt',
            field=models.ImageField(blank=True, help_text="To'lov cheki rasmi (ixtiyoriy)", null=True, upload_to='receipts/'),
        ),
    ]
