# Generated by Django 6.0.4 on 2026-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user_data',
            field=models.JSONField(default=dict, help_text='Temporary user registration data'),
        ),
    ]
